### ISSUE TITLE
Edit link to Lizenzen

### ISSUE THREAD

**Issue by kevinriex** [kevinriex/notfall.ratingen.de#18]
Der Link zu Lizenzen ist statisch. Er musste Dynamisch (Host unabhängig) sein

**Comment by kdev** [comment]
Ist "ratingen.de/lizenzen" ein guter Linktitel?

**Comment by kevinriex** [comment]
Jo

**Comment by kdev** [comment]
Top

**Comment by kdev** [comment]
I've added dynamic rendering to the link button in [35a0f83](https://github.com/kevinriex/notfall.ratingen.de/commit/35a0f8379fc1f1c6dd003c676038af0ea26d5e46)
